# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f775723a01d75b39544a8eb05da78a77aa2c867efdcf0c091a9012fdb2bc1ec7b1dab7d9f2a0d38d88e88c62a32eda3ce3d781c31cc677bd436bf1573c571cd

test:
  secret_key_base: 1e42bfa75d2067d46d3f9e805c5a85e4e1ac137f63a46a8ac00a4fcded310fa407318ca679307af9b3f6037e5fda92d84786ffa61ce64986ef2278d76a552039

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
